# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  lapiquette-app:
    image: lapiquette
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:Default:Default@cluster0.yv4tr.mongodb.net/LaPiquette
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://lapiquette-postgresql:5432/laPiquette
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "Default@cluster0.yv4tr.mongodb.net/LaPiquette:" prefix
    ports:
      - 8080:8080
  lapiquette-mongodb:
    image: mongo:4.4.6
    # If you want to expose these ports outside your dev PC,
    # remove the "Default@cluster0.yv4tr.mongodb.net/LaPiquette:" prefix
    ports:
      - 27017:27017
    # volumes:
    #   - ~/volumes/jhipster/LaPiquette/mongodb/:/data/db/
